services:
  web:
    build: ./www
    container_name: webserver
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    environment:
      DB_HOST: dbserver
      DB_NAME: appdb
      DB_USER: appuser
      DB_PASSWORD: secret123
    networks:
      - DigitalWorkshop

networks:
  DigitalWorkshop:
    external: true